name: Hola Github-Actions(name)
on: push

jobs: 
  primera_tarea:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: saluddar
        run: echo "Hola Github Actions from ubuntu container"
        
